# Generated by Django 4.2.4 on 2023-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
